/***
 * Klasse zur Nutzung der automatisch generierten Datenbankklassenobjekte
 * diese Klasse wurde manuell erstellt.
 * Diese Klasse wird evtl. in der Zukunft benötigt und muss dann fertig gestellt werden.
 * Aktuell erhällt diese Klasse nur zwei Beispielmethoden.
 ***/
             //Folgenden Zeilen schreibt man ins Hauptprogramm, um autogeneratedDB zu nutzen:
            //AutoDBContext autocontext = new AutoDBContext();
            //autocontext.fillDB();
            //autocontext.getABOs();
            //Evtl. müssen wir die automatisch generierte Klasse nehmen. Sie regelt den Umgang mit der DB besser.
            //Kapitel dazu: http://openbook.rheinwerk-verlag.de/visual_csharp_2012/1997_37_001.html#dodtp97eab997-f0da-4739-b514-a73fccd2935a
/***
 * Der Inhalt der App.Config muss in die App.Config der hauptanwendung im ersten Zweig kopiert werden.
**/
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using System.ComponentModel;
using System.IO;
using System.Reflection;
using System.Diagnostics;
using System.Threading;
using System.Data.Entity;

namespace autogeneratedDB
{
    public class AutoDBContext
    {

        public void getABOs()
            {
using(DBVerbindung db = new DBVerbindung())
    {
                                var abos = db.abo;
                //Console.WriteLine(abos.ToTraceString()); //gibt die SQL-Query aus
                foreach(var abo in abos)
                    Console.WriteLine("{0} {1} {2} {3} {4}", abo.id, abo.ausgabe_bis, abo.ausgabe_von, abo.bezahlt_bis, abo.bezahlt_von, abo.bezahlt_am);
    }
}

        public void fillDB()
        {
            using(DBVerbindung db = new DBVerbindung())
                {
                kunden kunde = kunden.Createkunden(0, "", "", "", "", "", 12345, "", "", "", "", "", "", 1, 0, 0, 0, 0);
                bemerkung bm = bemerkung.Createbemerkung(0, "test", 0);
                bm.kunden = kunde;
                                db.AddTobemerkung(bm);
            abo cabo = new abo();
                cabo.ausgabe_bis = 0;
                cabo.ausgabe_von = 0;
                cabo.bezahlt_am = 0;
                cabo.bezahlt_bis = 0;
                cabo.bezahlt_von = 0;
                cabo.id = 0;
                cabo.bemerkung = bm;
                                db.AddToabo(cabo);
                db.SaveChanges();
                Console.WriteLine("Datenbank aktualisiert... Neue ID: {0}", cabo.id);
            }
        }

    }//end class
}//end namespace
